/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteDocinhosRouteImport } from './routes/_site/docinhos'
import { Route as SiteBolosDePoteRouteImport } from './routes/_site/bolos-de-pote'
import { Route as SiteBolosDeFestaRouteImport } from './routes/_site/bolos-de-festa'
import { Route as SiteBolosCaseirosRouteImport } from './routes/_site/bolos-caseiros'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocinhosRoute = SiteDocinhosRouteImport.update({
  id: '/docinhos',
  path: '/docinhos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBolosDePoteRoute = SiteBolosDePoteRouteImport.update({
  id: '/bolos-de-pote',
  path: '/bolos-de-pote',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBolosDeFestaRoute = SiteBolosDeFestaRouteImport.update({
  id: '/bolos-de-festa',
  path: '/bolos-de-festa',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBolosCaseirosRoute = SiteBolosCaseirosRouteImport.update({
  id: '/bolos-caseiros',
  path: '/bolos-caseiros',
  getParentRoute: () => SiteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/_public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/docinhos': typeof SiteDocinhosRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/docinhos': typeof SiteDocinhosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_site/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/_site/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/_site/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/_site/docinhos': typeof SiteDocinhosRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/bolos-caseiros'
    | '/bolos-de-festa'
    | '/bolos-de-pote'
    | '/docinhos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/bolos-caseiros'
    | '/bolos-de-festa'
    | '/bolos-de-pote'
    | '/docinhos'
  id:
    | '__root__'
    | '/_private'
    | '/_site'
    | '/_private/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_site/bolos-caseiros'
    | '/_site/bolos-de-festa'
    | '/_site/bolos-de-pote'
    | '/_site/docinhos'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docinhos': {
      id: '/_site/docinhos'
      path: '/docinhos'
      fullPath: '/docinhos'
      preLoaderRoute: typeof SiteDocinhosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bolos-de-pote': {
      id: '/_site/bolos-de-pote'
      path: '/bolos-de-pote'
      fullPath: '/bolos-de-pote'
      preLoaderRoute: typeof SiteBolosDePoteRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bolos-de-festa': {
      id: '/_site/bolos-de-festa'
      path: '/bolos-de-festa'
      fullPath: '/bolos-de-festa'
      preLoaderRoute: typeof SiteBolosDeFestaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bolos-caseiros': {
      id: '/_site/bolos-caseiros'
      path: '/bolos-caseiros'
      fullPath: '/bolos-caseiros'
      preLoaderRoute: typeof SiteBolosCaseirosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface SiteRouteChildren {
  SiteBolosCaseirosRoute: typeof SiteBolosCaseirosRoute
  SiteBolosDeFestaRoute: typeof SiteBolosDeFestaRoute
  SiteBolosDePoteRoute: typeof SiteBolosDePoteRoute
  SiteDocinhosRoute: typeof SiteDocinhosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBolosCaseirosRoute: SiteBolosCaseirosRoute,
  SiteBolosDeFestaRoute: SiteBolosDeFestaRoute,
  SiteBolosDePoteRoute: SiteBolosDePoteRoute,
  SiteDocinhosRoute: SiteDocinhosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
