/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as SiteDocinhosRouteImport } from './routes/_site/docinhos'
import { Route as SiteBolosVulcaoRouteImport } from './routes/_site/bolos-vulcao'
import { Route as SiteBolosFitRouteImport } from './routes/_site/bolos-fit'
import { Route as SiteBolosDePoteRouteImport } from './routes/_site/bolos-de-pote'
import { Route as SiteBolosDeFestaRouteImport } from './routes/_site/bolos-de-festa'
import { Route as SiteBolosCaseirosRouteImport } from './routes/_site/bolos-caseiros'
import { Route as SiteBolosBombomRouteImport } from './routes/_site/bolos-bombom'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppOrderFormRouteImport } from './routes/app/order.form'
import { Route as AuthOrganizationNewRouteImport } from './routes/_auth/organization.new'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const SiteDocinhosRoute = SiteDocinhosRouteImport.update({
  id: '/docinhos',
  path: '/docinhos',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosVulcaoRoute = SiteBolosVulcaoRouteImport.update({
  id: '/bolos-vulcao',
  path: '/bolos-vulcao',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosFitRoute = SiteBolosFitRouteImport.update({
  id: '/bolos-fit',
  path: '/bolos-fit',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosDePoteRoute = SiteBolosDePoteRouteImport.update({
  id: '/bolos-de-pote',
  path: '/bolos-de-pote',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosDeFestaRoute = SiteBolosDeFestaRouteImport.update({
  id: '/bolos-de-festa',
  path: '/bolos-de-festa',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosCaseirosRoute = SiteBolosCaseirosRouteImport.update({
  id: '/bolos-caseiros',
  path: '/bolos-caseiros',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBolosBombomRoute = SiteBolosBombomRouteImport.update({
  id: '/bolos-bombom',
  path: '/bolos-bombom',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppOrderFormRoute = AppOrderFormRouteImport.update({
  id: '/order/form',
  path: '/order/form',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthOrganizationNewRoute = AuthOrganizationNewRouteImport.update({
  id: '/organization/new',
  path: '/organization/new',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bolos-bombom': typeof SiteBolosBombomRoute
  '/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/bolos-fit': typeof SiteBolosFitRoute
  '/bolos-vulcao': typeof SiteBolosVulcaoRoute
  '/docinhos': typeof SiteDocinhosRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/organization/new': typeof AuthOrganizationNewRoute
  '/app/order/form': typeof AppOrderFormRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bolos-bombom': typeof SiteBolosBombomRoute
  '/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/bolos-fit': typeof SiteBolosFitRoute
  '/bolos-vulcao': typeof SiteBolosVulcaoRoute
  '/docinhos': typeof SiteDocinhosRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/organization/new': typeof AuthOrganizationNewRoute
  '/app/order/form': typeof AppOrderFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_site': typeof SiteRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_site/bolos-bombom': typeof SiteBolosBombomRoute
  '/_site/bolos-caseiros': typeof SiteBolosCaseirosRoute
  '/_site/bolos-de-festa': typeof SiteBolosDeFestaRoute
  '/_site/bolos-de-pote': typeof SiteBolosDePoteRoute
  '/_site/bolos-fit': typeof SiteBolosFitRoute
  '/_site/bolos-vulcao': typeof SiteBolosVulcaoRoute
  '/_site/docinhos': typeof SiteDocinhosRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/_site/': typeof SiteIndexRoute
  '/_auth/organization/new': typeof AuthOrganizationNewRoute
  '/app/order/form': typeof AppOrderFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/bolos-bombom'
    | '/bolos-caseiros'
    | '/bolos-de-festa'
    | '/bolos-de-pote'
    | '/bolos-fit'
    | '/bolos-vulcao'
    | '/docinhos'
    | '/app/dashboard'
    | '/organization/new'
    | '/app/order/form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/bolos-bombom'
    | '/bolos-caseiros'
    | '/bolos-de-festa'
    | '/bolos-de-pote'
    | '/bolos-fit'
    | '/bolos-vulcao'
    | '/docinhos'
    | '/app/dashboard'
    | '/organization/new'
    | '/app/order/form'
  id:
    | '__root__'
    | '/_auth'
    | '/_site'
    | '/app'
    | '/_auth/login'
    | '/_auth/register'
    | '/_site/bolos-bombom'
    | '/_site/bolos-caseiros'
    | '/_site/bolos-de-festa'
    | '/_site/bolos-de-pote'
    | '/_site/bolos-fit'
    | '/_site/bolos-vulcao'
    | '/_site/docinhos'
    | '/app/dashboard'
    | '/_site/'
    | '/_auth/organization/new'
    | '/app/order/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_site/docinhos': {
      id: '/_site/docinhos'
      path: '/docinhos'
      fullPath: '/docinhos'
      preLoaderRoute: typeof SiteDocinhosRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-vulcao': {
      id: '/_site/bolos-vulcao'
      path: '/bolos-vulcao'
      fullPath: '/bolos-vulcao'
      preLoaderRoute: typeof SiteBolosVulcaoRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-fit': {
      id: '/_site/bolos-fit'
      path: '/bolos-fit'
      fullPath: '/bolos-fit'
      preLoaderRoute: typeof SiteBolosFitRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-de-pote': {
      id: '/_site/bolos-de-pote'
      path: '/bolos-de-pote'
      fullPath: '/bolos-de-pote'
      preLoaderRoute: typeof SiteBolosDePoteRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-de-festa': {
      id: '/_site/bolos-de-festa'
      path: '/bolos-de-festa'
      fullPath: '/bolos-de-festa'
      preLoaderRoute: typeof SiteBolosDeFestaRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-caseiros': {
      id: '/_site/bolos-caseiros'
      path: '/bolos-caseiros'
      fullPath: '/bolos-caseiros'
      preLoaderRoute: typeof SiteBolosCaseirosRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bolos-bombom': {
      id: '/_site/bolos-bombom'
      path: '/bolos-bombom'
      fullPath: '/bolos-bombom'
      preLoaderRoute: typeof SiteBolosBombomRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/order/form': {
      id: '/app/order/form'
      path: '/order/form'
      fullPath: '/app/order/form'
      preLoaderRoute: typeof AppOrderFormRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/organization/new': {
      id: '/_auth/organization/new'
      path: '/organization/new'
      fullPath: '/organization/new'
      preLoaderRoute: typeof AuthOrganizationNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthOrganizationNewRoute: typeof AuthOrganizationNewRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthOrganizationNewRoute: AuthOrganizationNewRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SiteRouteRouteChildren {
  SiteBolosBombomRoute: typeof SiteBolosBombomRoute
  SiteBolosCaseirosRoute: typeof SiteBolosCaseirosRoute
  SiteBolosDeFestaRoute: typeof SiteBolosDeFestaRoute
  SiteBolosDePoteRoute: typeof SiteBolosDePoteRoute
  SiteBolosFitRoute: typeof SiteBolosFitRoute
  SiteBolosVulcaoRoute: typeof SiteBolosVulcaoRoute
  SiteDocinhosRoute: typeof SiteDocinhosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteBolosBombomRoute: SiteBolosBombomRoute,
  SiteBolosCaseirosRoute: SiteBolosCaseirosRoute,
  SiteBolosDeFestaRoute: SiteBolosDeFestaRoute,
  SiteBolosDePoteRoute: SiteBolosDePoteRoute,
  SiteBolosFitRoute: SiteBolosFitRoute,
  SiteBolosVulcaoRoute: SiteBolosVulcaoRoute,
  SiteDocinhosRoute: SiteDocinhosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrderFormRoute: typeof AppOrderFormRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrderFormRoute: AppOrderFormRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
